### ISSUE TITLE
Add examples of how data is sent to different routes

### ISSUE THREAD

**Issue by knownasilya** [thoov/ember-websockets#12]
If it's even possible :smile: 

Maybe a chat room example where a new route is a different room or something.

**Comment by yratanov** [comment]
@thoov I believe I have related question. I have several chat rooms with routes e.g. `room/1`, `room/2`, etc.
Currently I have the following code:

```coffee
 updateSocketURL: ->
    @set('socketURL', "wss://localhost/chat/#{@modelFor('room').get('id')}")

  setupController: (controller, model)->
    @updateSocketURL()
    @_super(controller, model)
```
So the socket url is updated every time route changes, but ember-websocket uses previously created socket anyway. How can I close/open socket when route changes? Am I doing something wrong?

**Comment by yratanov** [comment]
ok, I ended up with this solution:
```coffee
updateSocketURL: (model)->
    modelId = model.get('id')
    @get('socketConfigurations').push
      key: "chat-#{modelId}"
      socketURL:"wss://localhost/chat/#{modelId}"

  setupController: (controller, model)->
    @updateSocketURL(model)
    @_super(controller, model)
```

Not so pretty, but working...

**Comment by thoov** [comment]
@yratanov Thanks for the question! Your first way that you listed should work but when I tested this locally I discovered a bug. The issue that you pointed out is that I was relying on the deactivate method to be called in order to indicate when I should close the socket. However if you have a route with a dynamic segment and you transition from say room/1 to room/123 then deactivate never gets called and thus the original socket never closes. I have a fix for this and I will push an update to npm right now. If you could download v0.6.0 and try it out and let me know if it is working for you I would greatly appreciate it.

**Comment by thoov** [comment]
I am closing this issue. I have updated the readme for both of these examples
