### ISSUE TITLE
Implement sub protocol STOMP

### ISSUE THREAD

**Issue by mervinva** [thoov/ember-websockets#143]
How to implement STOMP using the addon ?

**Comment by peavers** [comment]
Would also like to know...

**Comment by Dan-Ste** [comment]
I'm also curious to know

**Comment by thoov** [comment]
I do not have any knowledge of STOMP so if any of you could add to this it would be great. Basically 1 of 2 things has to happen:

1) Implement STOMP with native window.WebSockets. After researching for just a few minutes this doesn't seem like passing 'STOMP' as a protocol such as `new WebSocket('ws://example.com', ['STOMP']);` will work (again correct me if I'm wrong). If this assumption is true then that leads us to number 2.

2) Use some kind of third party library such as (https://github.com/jmesnil/stomp-websocket) and use it in the same vain as I am doing with socket-io. The problem here is that the library I linked to here is no longer maintained so I don't know if that is the best direction to go with. Do any of you know of a JS library that you use / like?

**Comment by peavers** [comment]
I've hacked STOMP into my ember app in the following way, it's dirty and quick but works as an example/something to work from for anyone looking. 

I'm using the following libraries; 
```
    "sockjs-client": "^1.1.4",
    "stompjs": "^2.3.3"
```
Then on any route it's as simple as doing
```
import Ember from "ember";
import RSVP from "rsvp";
import Stomp from 'npm:stompjs';
import SockJS from 'npm:sockjs-client';

const {Route, get} = Ember;

export default Route.extend({

  setupController(controller, models) {
    controller.setProperties(models);

    // Spring Cloud backend
    let stompClient = Stomp.over(new SockJS('http://localhost:8080/subscribe'));
    let store = this.get('store');

    stompClient.connect({}, function () {
      stompClient.subscribe("/queue/notify", notification => {

        // Could put a callback or some other function here, I'm just using it to push a record into the 
            store
        store.pushPayload(JSON.parse(notification.body));
      });
    });
  },
});
```
There is plenty wrong with the above code, and as @thoov  said looking at how he's implemented `socket-io` and implementing a solution such as that would be the way to go.

**Comment by Dan-Ste** [comment]
I use STOMP the same way as @peavers showed with Java Spring and its STOMP implementation on the backend.
