### ISSUE TITLE
Cannot read property 'commit' of null

### ISSUE THREAD

**Issue by drummy2** [thoov/ember-websockets#168]
I followed the install guide...

ember install ember-websockets

I copied the example component and then called the component in my template.  I would expect sensible "could not connect" but instead get some error about Cannot read property 'commit' of null.

It looks like it is attempting to get some ._env?

**Comment by thoov** [comment]
@drummy2 Thanks for the issue. I just ran the following steps:

```
ember new test-app
ember install ember-websockets
```

Then I copied the example component into the app started the server. I get the following message: "WebSocket connection to 'ws://localhost:7000/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED". This is the expected behavior. Could you send me the steps you ran which resulted in that error?

**Comment by drummy2** [comment]
I didn't really do much which is why I think I am missing a step or have forgotten something.
I am working in an addon dummy app so...

```
ember addon my-web-sockets
ember install ember-websockets
ember g component web-socket

```
Then copied and pasted the example into my component.
Then added my component to the application handlebars and ran the addon using

`ember s`

**Comment by thoov** [comment]
I tested on ember-cli & ember-source 3.7.0 and this appear to be working correctly. I then downgraded to the versions that you listed (ember-cli 3.0.2 & ember-source 3.0.0) and was able to see the error. Generally I try to only support back to the current LTS version which would be (3.4). Is it possible to use a newer version of ember-cli?

**Comment by drummy2** [comment]
I certainly can upgrade to 3.4, I will  do that now.  Thank you for your help @thoov
