### ISSUE TITLE
Cannot reconnect after closeSocketFor()

### ISSUE THREAD

**Issue by JDillon522** [thoov/ember-websockets#53]
I have a socket set in one of my components and I have the following set:

```
willDestroyElement: function() {
    this.get('socketIOService').closeSocketFor(this.get('socketPath'))
}
```

If I dont close the socket this way when transitioning I get the following error:

> Uncaught Error: Assertion Failed: calling set on destroyed object

Whats happening is that my socket connection is still listening for events from the API and its trying to call methods to set properties that were destroyed when I transitioned to another route. 

So when I close the socket and return to the route it fails to reconnect. Heres my socket setup:

```
socketSetup: (function () {
      var socket, socketPath;
      socket = this.get('socket');
      socketPath = this.config.Variables.API_URL + '/service/' + this.get('service.id');
      socket = this.get('socketIOService').socketFor(socketPath);
      this.set('socketPath', socketPath);
      console.log('TRYING TO CONNECT', this.get('socketIOService'));
      
     socket.on('close', function (closeData) {
        console.log('CLOSE DATA', closeData);
        return socket.reconnect();
      });

      socket.on('connect', function (event) {
        // This does not fire when returning to the route
        console.log('CONNECTING');
        socket.on('computerAvailable', this.computerAvailable, this);
        socket.on('computerUnavailable', this.computerUnavailable, this);
        socket.on('portalAvailable', this.portalAvailable, this);
      }, this);

      socket.on('open', function (openData) {
        return console.log('OPENING', openData);
      }, this);

      socket.on('close', function (closeData) {
        return console.log('CLOSING', closeData);
      }, this);

      socket.on('error', function () {
        console.log('CONNECTION ERROR');
        return this.disruptedFeature;
      }, this);

      socket.on('disconnect', this.disruptedFeature, this);

      socket.on('reconnect', function (reconnect) {
        console.log('RECONNECT EVENT');
        this.set('reconnectAttemptCounter', 0);
        return this.featureReconnect(reconnect);
      }, this);

      socket.on('reconnect_attempt', function (attempt) {
        console.log('RECONNECT ATTEMPT');
        this.incrementProperty('reconnectAttemptCounter');
        if (this.get('reconnectAttemptCounter') < this.get('reconnectAttemptLimit')) {
          return this.disruptedFeature(attempt);
        }
      }, this);

      socket.on('reconnect_error', function (error) {
        console.log('RECONNECT ERR');
        if (this.get('reconnectAttemptCounter') > this.get('reconnectAttemptLimit')) {
          return this.featureUnavailable(error);
        }
      }, this);

      return socket.on('reconnect_failed', this.featureUnavailable, this);
    }).on('init')
```

Any ideas on how to reconnect?

**Comment by JDillon522** [comment]
also, trying to call `socket.socket.open()` above the connection event doesnt work either.

**Comment by thoov** [comment]
@JDillon522 Can you download version 1.2.4 and see if you are still seeing this issue?

**Comment by JDillon522** [comment]
Awesome! That totally fixes it. For posterity's sake, and to suit my own curiosity, what was the underlying issue? I took a look at your changes but I'd love to "hear it from the horses mouth".

**Comment by thoov** [comment]
There were 2 issues. The first is that when you close a socket it was setting the internal property `sockets` to a standard array instead of an ember array (https://github.com/thoov/ember-websockets/blob/f9e2dc2cbcc6657ba61dab5bbbda967333f3f0e5/app/services/socket-io.js#L84). This was causing an error whenever you transition back to the page as `pushObject` was not defined here anymore (https://github.com/thoov/ember-websockets/blob/f9e2dc2cbcc6657ba61dab5bbbda967333f3f0e5/app/services/socket-io.js#L40).

The second issue is that when calling io('some_url') after closing a socket.io connection it was returning a  socket from its cache instead of creating a new one so I need to "clean it up" (https://github.com/thoov/ember-websockets/blob/f9e2dc2cbcc6657ba61dab5bbbda967333f3f0e5/app/services/socket-io.js#L77) and reconnect it (https://github.com/thoov/ember-websockets/blob/f9e2dc2cbcc6657ba61dab5bbbda967333f3f0e5/app/services/socket-io.js#L38).

Another note about the second issue is that I need to be smarter about the clean up as I think what I added isnt 100% correct but it will work for now. Hopefully this helps and let me know if you need anything else clarified.
